# Generated by Django 3.0.3 on 2020-05-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=50)),
                ('heroname', models.CharField(max_length=50)),
                ('heroinename', models.CharField(max_length=50)),
                ('producername', models.CharField(max_length=50)),
                ('Directorname', models.CharField(max_length=50)),
                ('Budget', models.FloatField(max_length=50)),
                ('noofworkers', models.IntegerField(max_length=10)),
            ],
        ),
    ]
